import "Windows.Foundation.idl";
import "Windows.ApplicationModel.idl";
import "Windows.Web.Http.idl";

namespace App2App
{
	enum App2AppCallResultStatus
	{
		Completed,
		TimedOut,
		Failed
	};

	runtimeclass App2AppCallResult
	{
		App2AppCallResult(App2AppCallResultStatus status, HRESULT error, Object result);

		App2AppCallResultStatus Status{ get; };
		HRESULT ExtendedError{ get; };
		Object Result{ get; };
	}

	interface IApp2AppConnection
	{
		Windows.Foundation.IAsyncOperation<App2AppCallResult> InvokeAsync(Windows.Foundation.Collections.IPropertySet args);
		void Close();
	};

	interface IApp2AppHttpConnection
	{
		Windows.Foundation.IAsyncOperation<Windows.Web.Http.HttpResponseMessage> InvokeAsync(Windows.Web.Http.HttpRequestMessage message);
		void Close();
	};

	enum App2AppConnectionStyleKind
	{
		PropertySet,
		HttpMessage,
		String,
		CommandLine,
		StdInOut,
	};

	runtimeclass App2AppProviderInfo
	{
		Windows.ApplicationModel.Package Package { get; };
		String Service{ get; };
		Guid ActivationId{ get; };
		String AppExecAlias{ get; };
		String DescriptionFilePath{ get; };
		String InterfaceFilePath{ get; };
		App2AppConnectionStyleKind ConnectionStyle{ get; };

		Object Connect();
	}

	delegate IApp2AppConnection App2AppConnectionHostFactory();
	delegate IApp2AppHttpConnection App2AppHttpConnectionHostFactory();

	static runtimeclass App2AppConnection
	{
		static App2AppProviderInfo[] GetServiceProviders(String service);
		static App2AppProviderInfo[] GetPackageServices(String packageFamilyName);

		[method_name("GetPackageServicesSpecific")]
		static App2AppProviderInfo[] GetPackageServices(String packageFamilyName, String service);

		static IApp2AppConnection Connect(String packageFamilyName, String service);
		static IApp2AppHttpConnection ConnectHttp(String packageFamilyName, String service);

		static void RegisterHost(Guid hostId, App2AppConnectionHostFactory factory);
		static void RegisterHttpHost(Guid hostId, App2AppHttpConnectionHostFactory factory);

		static void DeregisterHost(Guid hostId);
		static void UnregisterAllHosts();
	}
}
